// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtswhlvhctqhewkrfhhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0c3dobHZoY3RxaGV3a3JmaGhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMzQ3MzYsImV4cCI6MjA1ODYxMDczNn0.J_bhg4l7xmwgmsRFvmODeooYp1DbLBoqgFtxqzlkx7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);